<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Subject;
use App\Models\School;

class SubjectSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $schools = School::all();

        if ($schools->isEmpty()) {
            $this->command->info('No schools found. Skipping SubjectSeeder.');
            return;
        }

        $subjectsData = $this->getSubjectsData();

        foreach ($schools as $school) {
            $this->command->info("Seeding subjects for school: {$school->name} (ID: {$school->id})");

            foreach ($subjectsData as $curriculum => $levels) {
                $this->command->line("  - Processing {$curriculum} curriculum...");

                foreach ($levels as $levelKey => $levelData) {
                    $this->command->line("    - Seeding subjects for level: {$levelKey}");

                    foreach ($levelData['subjects'] as $subjectDetails) {
                        Subject::updateOrCreate(
                            [
                                'school_id' => $school->id,
                                'code'      => $subjectDetails['code'],
                            ],
                            [
                                'name'                    => $subjectDetails['name'],
                                'curriculum_type'         => $curriculum,
                                'grade_level'             => $levelData['grade_level'],
                                'level'                   => $levelData['level'],
                                'pathway'                 => $levelData['pathway'] ?? null,
                                'category'                => $subjectDetails['category'],
                                'is_core'                 => $subjectDetails['is_core'],

                                // KICD Fields
                                'is_kicd_compulsory'      => $subjectDetails['is_kicd_compulsory'] ?? $subjectDetails['is_core'],
                                'learning_area'           => $subjectDetails['learning_area'] ?? $subjectDetails['category'],
                                'minimum_weekly_periods'  => $subjectDetails['min_periods'] ?? 3,
                                'maximum_weekly_periods'  => $subjectDetails['max_periods'] ?? 8,
                                'requires_lab'            => $subjectDetails['requires_lab'] ?? false,
                                'cbc_pathway'             => $levelData['pathway'] ?? 'All',
                                'kicd_code'               => $subjectDetails['kicd_code'] ?? null,
                            ]
                        );
                    }
                }
            }
        }

        $this->command->info('✓ SubjectSeeder finished successfully!');
    }

    /**
     * Returns a structured array of subjects for Kenyan curricula with KICD data.
     *
     * Structure:
     *   curriculum_type => [
     *     level_key => [
     *       'level'       => educational level string,
     *       'grade_level' => human-readable grade band,
     *       'pathway'     => (optional) STEM | Arts | Social Sciences,
     *       'subjects'    => [...],
     *     ],
     *   ]
     */
    private function getSubjectsData(): array
    {
        return [
            // ─────────────────────────────────────────────────────────────
            // CBC CURRICULUM
            // ─────────────────────────────────────────────────────────────
            'CBC' => [

                // ── Pre-Primary (PP1–PP2) ─────────────────────────────────
                'pre_primary' => [
                    'level'       => 'Pre-Primary',
                    'grade_level' => 'PP1-PP2',
                    'pathway'     => null,
                    'subjects'    => [
                        [
                            'name'                => 'Language Activities',
                            'code'                => 'CBC-PP-LAN',
                            'category'            => 'Languages',
                            'learning_area'       => 'Language Activities',
                            'is_core'             => true,
                            'is_kicd_compulsory'  => true,
                            'min_periods'         => 5,
                            'max_periods'         => 7,
                            'kicd_code'           => 'PP-LA-001',
                        ],
                        [
                            'name'                => 'Mathematical Activities',
                            'code'                => 'CBC-PP-MAT',
                            'category'            => 'Mathematics',
                            'learning_area'       => 'Mathematical Activities',
                            'is_core'             => true,
                            'is_kicd_compulsory'  => true,
                            'min_periods'         => 5,
                            'max_periods'         => 7,
                            'kicd_code'           => 'PP-MA-001',
                        ],
                        [
                            'name'                => 'Environmental Activities',
                            'code'                => 'CBC-PP-ENV',
                            'category'            => 'Sciences',
                            'learning_area'       => 'Environmental Activities',
                            'is_core'             => true,
                            'is_kicd_compulsory'  => true,
                            'min_periods'         => 4,
                            'max_periods'         => 6,
                            'kicd_code'           => 'PP-EA-001',
                        ],
                        [
                            'name'                => 'Psychomotor & Creative Activities',
                            'code'                => 'CBC-PP-PSY',
                            'category'            => 'Creative Arts',
                            'learning_area'       => 'Psychomotor & Creative Activities',
                            'is_core'             => true,
                            'is_kicd_compulsory'  => true,
                            'min_periods'         => 4,
                            'max_periods'         => 6,
                            'kicd_code'           => 'PP-PCA-001',
                        ],
                        [
                            'name'                => 'Religious Education Activities',
                            'code'                => 'CBC-PP-RE',
                            'category'            => 'Humanities',
                            'learning_area'       => 'Religious Education',
                            'is_core'             => true,
                            'is_kicd_compulsory'  => true,
                            'min_periods'         => 2,
                            'max_periods'         => 3,
                            'kicd_code'           => 'PP-RE-001',
                        ],
                    ],
                ],

                // ── Lower Primary (Grade 1–3) ──────────────────────────────
                'lower_primary' => [
                    'level'       => 'Primary',
                    'grade_level' => 'Grade 1-3',
                    'pathway'     => null,
                    'subjects'    => [
                        [
                            'name'                => 'Literacy Activities',
                            'code'                => 'CBC-G13-LIT',
                            'category'            => 'Languages',
                            'learning_area'       => 'Literacy',
                            'is_core'             => true,
                            'is_kicd_compulsory'  => true,
                            'min_periods'         => 6,
                            'max_periods'         => 8,
                            'kicd_code'           => 'LP-LIT-001',
                        ],
                        [
                            'name'                => 'Kiswahili Language Activities',
                            'code'                => 'CBC-G13-KIS',
                            'category'            => 'Languages',
                            'learning_area'       => 'Languages',
                            'is_core'             => true,
                            'is_kicd_compulsory'  => true,
                            'min_periods'         => 5,
                            'max_periods'         => 6,
                            'kicd_code'           => 'LP-KIS-001',
                        ],
                        [
                            'name'                => 'English Language Activities',
                            'code'                => 'CBC-G13-ENG',
                            'category'            => 'Languages',
                            'learning_area'       => 'Languages',
                            'is_core'             => true,
                            'is_kicd_compulsory'  => true,
                            'min_periods'         => 5,
                            'max_periods'         => 6,
                            'kicd_code'           => 'LP-ENG-001',
                        ],
                        [
                            'name'                => 'Mathematical Activities',
                            'code'                => 'CBC-G13-MAT',
                            'category'            => 'Mathematics',
                            'learning_area'       => 'Mathematics',
                            'is_core'             => true,
                            'is_kicd_compulsory'  => true,
                            'min_periods'         => 5,
                            'max_periods'         => 7,
                            'kicd_code'           => 'LP-MAT-001',
                        ],
                        [
                            'name'                => 'Environmental Activities',
                            'code'                => 'CBC-G13-ENV',
                            'category'            => 'Sciences',
                            'learning_area'       => 'Environmental Activities',
                            'is_core'             => true,
                            'is_kicd_compulsory'  => true,
                            'min_periods'         => 4,
                            'max_periods'         => 5,
                            'kicd_code'           => 'LP-ENV-001',
                        ],
                        [
                            'name'                => 'Creative Arts & Sports',
                            'code'                => 'CBC-G13-CAS',
                            'category'            => 'Creative Arts',
                            'learning_area'       => 'Creative Arts',
                            'is_core'             => true,
                            'is_kicd_compulsory'  => true,
                            'min_periods'         => 3,
                            'max_periods'         => 5,
                            'kicd_code'           => 'LP-CAS-001',
                        ],
                        [
                            'name'                => 'Religious Education',
                            'code'                => 'CBC-G13-RE',
                            'category'            => 'Humanities',
                            'learning_area'       => 'Religious Education',
                            'is_core'             => true,
                            'is_kicd_compulsory'  => true,
                            'min_periods'         => 2,
                            'max_periods'         => 3,
                            'kicd_code'           => 'LP-RE-001',
                        ],
                    ],
                ],

                // ── Upper Primary (Grade 4–6) ──────────────────────────────
                'upper_primary' => [
                    'level'       => 'Primary',
                    'grade_level' => 'Grade 4-6',
                    'pathway'     => null,
                    'subjects'    => [
                        [
                            'name'                => 'English',
                            'code'                => 'CBC-G46-ENG',
                            'category'            => 'Languages',
                            'learning_area'       => 'Languages',
                            'is_core'             => true,
                            'is_kicd_compulsory'  => true,
                            'min_periods'         => 5,
                            'max_periods'         => 6,
                            'kicd_code'           => 'UP-ENG-001',
                        ],
                        [
                            'name'                => 'Kiswahili',
                            'code'                => 'CBC-G46-KIS',
                            'category'            => 'Languages',
                            'learning_area'       => 'Languages',
                            'is_core'             => true,
                            'is_kicd_compulsory'  => true,
                            'min_periods'         => 4,
                            'max_periods'         => 5,
                            'kicd_code'           => 'UP-KIS-001',
                        ],
                        [
                            'name'                => 'Mathematics',
                            'code'                => 'CBC-G46-MAT',
                            'category'            => 'Mathematics',
                            'learning_area'       => 'Mathematics',
                            'is_core'             => true,
                            'is_kicd_compulsory'  => true,
                            'min_periods'         => 5,
                            'max_periods'         => 7,
                            'kicd_code'           => 'UP-MAT-001',
                        ],
                        [
                            'name'                => 'Science & Technology',
                            'code'                => 'CBC-G46-SCI',
                            'category'            => 'Sciences',
                            'learning_area'       => 'Science & Technology',
                            'is_core'             => true,
                            'is_kicd_compulsory'  => true,
                            'min_periods'         => 4,
                            'max_periods'         => 5,
                            'kicd_code'           => 'UP-SCI-001',
                        ],
                        [
                            'name'                => 'Social Studies',
                            'code'                => 'CBC-G46-SST',
                            'category'            => 'Humanities',
                            'learning_area'       => 'Social Studies',
                            'is_core'             => true,
                            'is_kicd_compulsory'  => true,
                            'min_periods'         => 3,
                            'max_periods'         => 4,
                            'kicd_code'           => 'UP-SST-001',
                        ],
                        [
                            'name'                => 'Religious Education',
                            'code'                => 'CBC-G46-RE',
                            'category'            => 'Humanities',
                            'learning_area'       => 'Religious Education',
                            'is_core'             => true,
                            'is_kicd_compulsory'  => true,
                            'min_periods'         => 2,
                            'max_periods'         => 3,
                            'kicd_code'           => 'UP-RE-001',
                        ],
                        [
                            'name'                => 'Creative Arts & Sports',
                            'code'                => 'CBC-G46-CAS',
                            'category'            => 'Creative Arts',
                            'learning_area'       => 'Creative Arts',
                            'is_core'             => true,
                            'is_kicd_compulsory'  => true,
                            'min_periods'         => 3,
                            'max_periods'         => 4,
                            'kicd_code'           => 'UP-CAS-001',
                        ],
                        [
                            'name'                => 'Agriculture',
                            'code'                => 'CBC-G46-AGR',
                            'category'            => 'Technical',
                            'learning_area'       => 'Applied Sciences',
                            'is_core'             => false,
                            'is_kicd_compulsory'  => false,
                            'min_periods'         => 2,
                            'max_periods'         => 3,
                            'kicd_code'           => 'UP-AGR-001',
                        ],
                    ],
                ],

                // ── Junior Secondary (Grade 7–9) ───────────────────────────
                'junior_secondary' => [
                    'level'       => 'Junior Secondary',
                    'grade_level' => 'Grade 7-9',
                    'pathway'     => null,           // No pathway split yet at JS level
                    'subjects'    => [
                        // Core (compulsory for ALL Grade 7–9 students)
                        [
                            'name'                => 'English',
                            'code'                => 'CBC-G79-ENG',
                            'category'            => 'Languages',
                            'learning_area'       => 'Languages',
                            'is_core'             => true,
                            'is_kicd_compulsory'  => true,
                            'min_periods'         => 5,
                            'max_periods'         => 6,
                            'kicd_code'           => 'JS-ENG-001',
                        ],
                        [
                            'name'                => 'Kiswahili',
                            'code'                => 'CBC-G79-KIS',
                            'category'            => 'Languages',
                            'learning_area'       => 'Languages',
                            'is_core'             => true,
                            'is_kicd_compulsory'  => true,
                            'min_periods'         => 4,
                            'max_periods'         => 5,
                            'kicd_code'           => 'JS-KIS-001',
                        ],
                        [
                            'name'                => 'Mathematics',
                            'code'                => 'CBC-G79-MAT',
                            'category'            => 'Mathematics',
                            'learning_area'       => 'Mathematics',
                            'is_core'             => true,
                            'is_kicd_compulsory'  => true,
                            'min_periods'         => 5,
                            'max_periods'         => 6,
                            'kicd_code'           => 'JS-MAT-001',
                        ],
                        [
                            'name'                => 'Integrated Science',
                            'code'                => 'CBC-G79-SCI',
                            'category'            => 'Sciences',
                            'learning_area'       => 'Science & Technology',
                            'is_core'             => true,
                            'is_kicd_compulsory'  => true,
                            'min_periods'         => 4,
                            'max_periods'         => 5,
                            'requires_lab'        => true,
                            'kicd_code'           => 'JS-SCI-001',
                        ],
                        [
                            'name'                => 'Pre-Technical & Pre-Career Studies',
                            'code'                => 'CBC-G79-TEC',
                            'category'            => 'Technical',
                            'learning_area'       => 'Science & Technology',
                            'is_core'             => true,
                            'is_kicd_compulsory'  => true,
                            'min_periods'         => 4,
                            'max_periods'         => 5,
                            'kicd_code'           => 'JS-TEC-001',
                        ],
                        [
                            'name'                => 'Social Studies',
                            'code'                => 'CBC-G79-SST',
                            'category'            => 'Humanities',
                            'learning_area'       => 'Social Studies',
                            'is_core'             => true,
                            'is_kicd_compulsory'  => true,
                            'min_periods'         => 4,
                            'max_periods'         => 5,
                            'kicd_code'           => 'JS-SST-001',
                        ],
                        [
                            'name'                => 'Religious Education',
                            'code'                => 'CBC-G79-RE',
                            'category'            => 'Humanities',
                            'learning_area'       => 'Religious Education',
                            'is_core'             => true,
                            'is_kicd_compulsory'  => true,
                            'min_periods'         => 2,
                            'max_periods'         => 3,
                            'kicd_code'           => 'JS-RE-001',
                        ],
                        // Optional / Elective subjects
                        [
                            'name'                => 'Computer Science',
                            'code'                => 'CBC-G79-CSC',
                            'category'            => 'Technical',
                            'learning_area'       => 'Science & Technology',
                            'is_core'             => false,
                            'is_kicd_compulsory'  => false,
                            'min_periods'         => 3,
                            'max_periods'         => 4,
                            'kicd_code'           => 'JS-CSC-001',
                        ],
                        [
                            'name'                => 'Visual Arts',
                            'code'                => 'CBC-G79-VIS',
                            'category'            => 'Creative Arts',
                            'learning_area'       => 'Creative Arts',
                            'is_core'             => false,
                            'is_kicd_compulsory'  => false,
                            'min_periods'         => 2,
                            'max_periods'         => 3,
                            'kicd_code'           => 'JS-VIS-001',
                        ],
                        [
                            'name'                => 'Performing Arts',
                            'code'                => 'CBC-G79-PER',
                            'category'            => 'Creative Arts',
                            'learning_area'       => 'Creative Arts',
                            'is_core'             => false,
                            'is_kicd_compulsory'  => false,
                            'min_periods'         => 2,
                            'max_periods'         => 3,
                            'kicd_code'           => 'JS-PER-001',
                        ],
                        [
                            'name'                => 'Home Science',
                            'code'                => 'CBC-G79-HOM',
                            'category'            => 'Technical',
                            'learning_area'       => 'Applied Sciences',
                            'is_core'             => false,
                            'is_kicd_compulsory'  => false,
                            'min_periods'         => 2,
                            'max_periods'         => 3,
                            'kicd_code'           => 'JS-HOM-001',
                        ],
                        [
                            'name'                => 'Agriculture',
                            'code'                => 'CBC-G79-AGR',
                            'category'            => 'Technical',
                            'learning_area'       => 'Applied Sciences',
                            'is_core'             => false,
                            'is_kicd_compulsory'  => false,
                            'min_periods'         => 2,
                            'max_periods'         => 3,
                            'kicd_code'           => 'JS-AGR-001',
                        ],
                    ],
                ],

                // ── Senior Secondary – STEM Pathway (Grade 10–12) ──────────
                'senior_secondary_stem' => [
                    'level'       => 'Senior Secondary',
                    'grade_level' => 'Grade 10-12',
                    'pathway'     => 'STEM',
                    'subjects'    => [
                        // Compulsory for ALL Senior Secondary pathways
                        [
                            'name'                => 'English',
                            'code'                => 'CBC-SS-ENG',
                            'category'            => 'Languages',
                            'learning_area'       => 'Languages',
                            'is_core'             => true,
                            'is_kicd_compulsory'  => true,
                            'min_periods'         => 5,
                            'max_periods'         => 6,
                            'kicd_code'           => 'SS-ENG-001',
                        ],
                        [
                            'name'                => 'Kiswahili',
                            'code'                => 'CBC-SS-KIS',
                            'category'            => 'Languages',
                            'learning_area'       => 'Languages',
                            'is_core'             => true,
                            'is_kicd_compulsory'  => true,
                            'min_periods'         => 4,
                            'max_periods'         => 5,
                            'kicd_code'           => 'SS-KIS-001',
                        ],
                        [
                            'name'                => 'Community Service Learning',
                            'code'                => 'CBC-SS-CSL',
                            'category'            => 'Humanities',
                            'learning_area'       => 'Social Studies',
                            'is_core'             => true,
                            'is_kicd_compulsory'  => true,
                            'min_periods'         => 1,
                            'max_periods'         => 2,
                            'kicd_code'           => 'SS-CSL-001',
                        ],
                        // STEM core pathway subjects
                        [
                            'name'                => 'Mathematics',
                            'code'                => 'CBC-SS-STEM-MAT',
                            'category'            => 'Mathematics',
                            'learning_area'       => 'Mathematics',
                            'is_core'             => true,
                            'is_kicd_compulsory'  => true,
                            'min_periods'         => 6,
                            'max_periods'         => 7,
                            'kicd_code'           => 'SS-STEM-MAT-001',
                        ],
                        [
                            'name'                => 'Physics',
                            'code'                => 'CBC-SS-STEM-PHY',
                            'category'            => 'Sciences',
                            'learning_area'       => 'Science & Technology',
                            'is_core'             => true,
                            'is_kicd_compulsory'  => false,
                            'min_periods'         => 5,
                            'max_periods'         => 6,
                            'requires_lab'        => true,
                            'kicd_code'           => 'SS-STEM-PHY-001',
                        ],
                        [
                            'name'                => 'Chemistry',
                            'code'                => 'CBC-SS-STEM-CHE',
                            'category'            => 'Sciences',
                            'learning_area'       => 'Science & Technology',
                            'is_core'             => true,
                            'is_kicd_compulsory'  => false,
                            'min_periods'         => 5,
                            'max_periods'         => 6,
                            'requires_lab'        => true,
                            'kicd_code'           => 'SS-STEM-CHE-001',
                        ],
                        [
                            'name'                => 'Biology',
                            'code'                => 'CBC-SS-STEM-BIO',
                            'category'            => 'Sciences',
                            'learning_area'       => 'Science & Technology',
                            'is_core'             => false,
                            'is_kicd_compulsory'  => false,
                            'min_periods'         => 5,
                            'max_periods'         => 6,
                            'requires_lab'        => true,
                            'kicd_code'           => 'SS-STEM-BIO-001',
                        ],
                        [
                            'name'                => 'Computer Science',
                            'code'                => 'CBC-SS-STEM-CSC',
                            'category'            => 'Technical',
                            'learning_area'       => 'Science & Technology',
                            'is_core'             => false,
                            'is_kicd_compulsory'  => false,
                            'min_periods'         => 4,
                            'max_periods'         => 5,
                            'kicd_code'           => 'SS-STEM-CSC-001',
                        ],
                        [
                            'name'                => 'Agriculture',
                            'code'                => 'CBC-SS-STEM-AGR',
                            'category'            => 'Technical',
                            'learning_area'       => 'Applied Sciences',
                            'is_core'             => false,
                            'is_kicd_compulsory'  => false,
                            'min_periods'         => 4,
                            'max_periods'         => 5,
                            'kicd_code'           => 'SS-STEM-AGR-001',
                        ],
                    ],
                ],

                // ── Senior Secondary – Arts & Sports Science Pathway (Grade 10–12) ──
                'senior_secondary_arts' => [
                    'level'       => 'Senior Secondary',
                    'grade_level' => 'Grade 10-12',
                    'pathway'     => 'Arts',
                    'subjects'    => [
                        // Compulsory cross-pathway subjects
                        [
                            'name'                => 'English',
                            'code'                => 'CBC-SS-ENG',        // shared code — upsert deduplicates
                            'category'            => 'Languages',
                            'learning_area'       => 'Languages',
                            'is_core'             => true,
                            'is_kicd_compulsory'  => true,
                            'min_periods'         => 5,
                            'max_periods'         => 6,
                            'kicd_code'           => 'SS-ENG-001',
                        ],
                        [
                            'name'                => 'Kiswahili',
                            'code'                => 'CBC-SS-KIS',
                            'category'            => 'Languages',
                            'learning_area'       => 'Languages',
                            'is_core'             => true,
                            'is_kicd_compulsory'  => true,
                            'min_periods'         => 4,
                            'max_periods'         => 5,
                            'kicd_code'           => 'SS-KIS-001',
                        ],
                        [
                            'name'                => 'Community Service Learning',
                            'code'                => 'CBC-SS-CSL',
                            'category'            => 'Humanities',
                            'learning_area'       => 'Social Studies',
                            'is_core'             => true,
                            'is_kicd_compulsory'  => true,
                            'min_periods'         => 1,
                            'max_periods'         => 2,
                            'kicd_code'           => 'SS-CSL-001',
                        ],
                        // Arts pathway-specific subjects
                        [
                            'name'                => 'Visual Arts',
                            'code'                => 'CBC-SS-ARTS-VIS',
                            'category'            => 'Creative Arts',
                            'learning_area'       => 'Creative Arts',
                            'is_core'             => true,
                            'is_kicd_compulsory'  => false,
                            'min_periods'         => 5,
                            'max_periods'         => 6,
                            'kicd_code'           => 'SS-ARTS-VIS-001',
                        ],
                        [
                            'name'                => 'Performing Arts',
                            'code'                => 'CBC-SS-ARTS-PER',
                            'category'            => 'Creative Arts',
                            'learning_area'       => 'Creative Arts',
                            'is_core'             => true,
                            'is_kicd_compulsory'  => false,
                            'min_periods'         => 5,
                            'max_periods'         => 6,
                            'kicd_code'           => 'SS-ARTS-PER-001',
                        ],
                        [
                            'name'                => 'Physical Education',
                            'code'                => 'CBC-SS-ARTS-PE',
                            'category'            => 'Physical Ed',
                            'learning_area'       => 'Physical Education',
                            'is_core'             => false,
                            'is_kicd_compulsory'  => false,
                            'min_periods'         => 4,
                            'max_periods'         => 5,
                            'kicd_code'           => 'SS-ARTS-PE-001',
                        ],
                        [
                            'name'                => 'Music',
                            'code'                => 'CBC-SS-ARTS-MUS',
                            'category'            => 'Creative Arts',
                            'learning_area'       => 'Creative Arts',
                            'is_core'             => false,
                            'is_kicd_compulsory'  => false,
                            'min_periods'         => 4,
                            'max_periods'         => 5,
                            'kicd_code'           => 'SS-ARTS-MUS-001',
                        ],
                        [
                            'name'                => 'Home Science',
                            'code'                => 'CBC-SS-ARTS-HOM',
                            'category'            => 'Technical',
                            'learning_area'       => 'Applied Sciences',
                            'is_core'             => false,
                            'is_kicd_compulsory'  => false,
                            'min_periods'         => 3,
                            'max_periods'         => 4,
                            'kicd_code'           => 'SS-ARTS-HOM-001',
                        ],
                    ],
                ],

                // ── Senior Secondary – Social Sciences Pathway (Grade 10–12) ──
                'senior_secondary_social' => [
                    'level'       => 'Senior Secondary',
                    'grade_level' => 'Grade 10-12',
                    'pathway'     => 'Social Sciences',
                    'subjects'    => [
                        // Compulsory cross-pathway subjects
                        [
                            'name'                => 'English',
                            'code'                => 'CBC-SS-ENG',
                            'category'            => 'Languages',
                            'learning_area'       => 'Languages',
                            'is_core'             => true,
                            'is_kicd_compulsory'  => true,
                            'min_periods'         => 5,
                            'max_periods'         => 6,
                            'kicd_code'           => 'SS-ENG-001',
                        ],
                        [
                            'name'                => 'Kiswahili',
                            'code'                => 'CBC-SS-KIS',
                            'category'            => 'Languages',
                            'learning_area'       => 'Languages',
                            'is_core'             => true,
                            'is_kicd_compulsory'  => true,
                            'min_periods'         => 4,
                            'max_periods'         => 5,
                            'kicd_code'           => 'SS-KIS-001',
                        ],
                        [
                            'name'                => 'Community Service Learning',
                            'code'                => 'CBC-SS-CSL',
                            'category'            => 'Humanities',
                            'learning_area'       => 'Social Studies',
                            'is_core'             => true,
                            'is_kicd_compulsory'  => true,
                            'min_periods'         => 1,
                            'max_periods'         => 2,
                            'kicd_code'           => 'SS-CSL-001',
                        ],
                        // Social Sciences pathway-specific subjects
                        [
                            'name'                => 'History & Citizenship',
                            'code'                => 'CBC-SS-SOC-HIS',
                            'category'            => 'Humanities',
                            'learning_area'       => 'Social Studies',
                            'is_core'             => true,
                            'is_kicd_compulsory'  => false,
                            'min_periods'         => 5,
                            'max_periods'         => 6,
                            'kicd_code'           => 'SS-SOC-HIS-001',
                        ],
                        [
                            'name'                => 'Geography',
                            'code'                => 'CBC-SS-SOC-GEO',
                            'category'            => 'Humanities',
                            'learning_area'       => 'Social Studies',
                            'is_core'             => true,
                            'is_kicd_compulsory'  => false,
                            'min_periods'         => 5,
                            'max_periods'         => 6,
                            'kicd_code'           => 'SS-SOC-GEO-001',
                        ],
                        [
                            'name'                => 'Business Studies',
                            'code'                => 'CBC-SS-SOC-BUS',
                            'category'            => 'Technical',
                            'learning_area'       => 'Applied Sciences',
                            'is_core'             => false,
                            'is_kicd_compulsory'  => false,
                            'min_periods'         => 4,
                            'max_periods'         => 5,
                            'kicd_code'           => 'SS-SOC-BUS-001',
                        ],
                        [
                            'name'                => 'Religious Education',
                            'code'                => 'CBC-SS-SOC-RE',
                            'category'            => 'Humanities',
                            'learning_area'       => 'Religious Education',
                            'is_core'             => false,
                            'is_kicd_compulsory'  => false,
                            'min_periods'         => 3,
                            'max_periods'         => 4,
                            'kicd_code'           => 'SS-SOC-RE-001',
                        ],
                        [
                            'name'                => 'Mathematics (Applied)',
                            'code'                => 'CBC-SS-SOC-MAT',
                            'category'            => 'Mathematics',
                            'learning_area'       => 'Mathematics',
                            'is_core'             => false,
                            'is_kicd_compulsory'  => false,
                            'min_periods'         => 4,
                            'max_periods'         => 5,
                            'kicd_code'           => 'SS-SOC-MAT-001',
                        ],
                    ],
                ],
            ],

            // ─────────────────────────────────────────────────────────────
            // 8-4-4 CURRICULUM
            // ─────────────────────────────────────────────────────────────
            '8-4-4' => [

                // ── Primary (Standard 1–4) ─────────────────────────────────
                'lower_primary_844' => [
                    'level'       => 'Primary',
                    'grade_level' => 'Standard 1-4',
                    'pathway'     => null,
                    'subjects'    => [
                        [
                            'name'                => 'English',
                            'code'                => '84-S14-ENG',
                            'category'            => 'Languages',
                            'learning_area'       => 'Languages',
                            'is_core'             => true,
                            'is_kicd_compulsory'  => true,
                            'min_periods'         => 6,
                            'max_periods'         => 7,
                            'kicd_code'           => '844-S14-ENG-001',
                        ],
                        [
                            'name'                => 'Kiswahili',
                            'code'                => '84-S14-KIS',
                            'category'            => 'Languages',
                            'learning_area'       => 'Languages',
                            'is_core'             => true,
                            'is_kicd_compulsory'  => true,
                            'min_periods'         => 5,
                            'max_periods'         => 6,
                            'kicd_code'           => '844-S14-KIS-001',
                        ],
                        [
                            'name'                => 'Mathematics',
                            'code'                => '84-S14-MAT',
                            'category'            => 'Mathematics',
                            'learning_area'       => 'Mathematics',
                            'is_core'             => true,
                            'is_kicd_compulsory'  => true,
                            'min_periods'         => 6,
                            'max_periods'         => 7,
                            'kicd_code'           => '844-S14-MAT-001',
                        ],
                        [
                            'name'                => 'Science & Agriculture',
                            'code'                => '84-S14-SCI',
                            'category'            => 'Sciences',
                            'learning_area'       => 'Sciences',
                            'is_core'             => true,
                            'is_kicd_compulsory'  => true,
                            'min_periods'         => 4,
                            'max_periods'         => 5,
                            'kicd_code'           => '844-S14-SCI-001',
                        ],
                        [
                            'name'                => 'Social Studies',
                            'code'                => '84-S14-SST',
                            'category'            => 'Humanities',
                            'learning_area'       => 'Social Studies',
                            'is_core'             => true,
                            'is_kicd_compulsory'  => true,
                            'min_periods'         => 3,
                            'max_periods'         => 4,
                            'kicd_code'           => '844-S14-SST-001',
                        ],
                        [
                            'name'                => 'Religious Education',
                            'code'                => '84-S14-RE',
                            'category'            => 'Humanities',
                            'learning_area'       => 'Religious Education',
                            'is_core'             => true,
                            'is_kicd_compulsory'  => true,
                            'min_periods'         => 2,
                            'max_periods'         => 3,
                            'kicd_code'           => '844-S14-RE-001',
                        ],
                        [
                            'name'                => 'Creative Arts',
                            'code'                => '84-S14-ART',
                            'category'            => 'Creative Arts',
                            'learning_area'       => 'Creative Arts',
                            'is_core'             => true,
                            'is_kicd_compulsory'  => true,
                            'min_periods'         => 2,
                            'max_periods'         => 3,
                            'kicd_code'           => '844-S14-ART-001',
                        ],
                    ],
                ],

                // ── Primary (Standard 5–8) ─────────────────────────────────
                'upper_primary_844' => [
                    'level'       => 'Primary',
                    'grade_level' => 'Standard 5-8',
                    'pathway'     => null,
                    'subjects'    => [
                        [
                            'name'                => 'English',
                            'code'                => '84-S58-ENG',
                            'category'            => 'Languages',
                            'learning_area'       => 'Languages',
                            'is_core'             => true,
                            'is_kicd_compulsory'  => true,
                            'min_periods'         => 6,
                            'max_periods'         => 7,
                            'kicd_code'           => '844-S58-ENG-001',
                        ],
                        [
                            'name'                => 'Kiswahili',
                            'code'                => '84-S58-KIS',
                            'category'            => 'Languages',
                            'learning_area'       => 'Languages',
                            'is_core'             => true,
                            'is_kicd_compulsory'  => true,
                            'min_periods'         => 5,
                            'max_periods'         => 6,
                            'kicd_code'           => '844-S58-KIS-001',
                        ],
                        [
                            'name'                => 'Mathematics',
                            'code'                => '84-S58-MAT',
                            'category'            => 'Mathematics',
                            'learning_area'       => 'Mathematics',
                            'is_core'             => true,
                            'is_kicd_compulsory'  => true,
                            'min_periods'         => 6,
                            'max_periods'         => 7,
                            'kicd_code'           => '844-S58-MAT-001',
                        ],
                        [
                            'name'                => 'Science',
                            'code'                => '84-S58-SCI',
                            'category'            => 'Sciences',
                            'learning_area'       => 'Sciences',
                            'is_core'             => true,
                            'is_kicd_compulsory'  => true,
                            'min_periods'         => 4,
                            'max_periods'         => 5,
                            'kicd_code'           => '844-S58-SCI-001',
                        ],
                        [
                            'name'                => 'Social Studies & Religious Education',
                            'code'                => '84-S58-SST',
                            'category'            => 'Humanities',
                            'learning_area'       => 'Social Studies',
                            'is_core'             => true,
                            'is_kicd_compulsory'  => true,
                            'min_periods'         => 4,
                            'max_periods'         => 5,
                            'kicd_code'           => '844-S58-SST-001',
                        ],
                        [
                            'name'                => 'Agriculture',
                            'code'                => '84-S58-AGR',
                            'category'            => 'Technical',
                            'learning_area'       => 'Applied Sciences',
                            'is_core'             => false,
                            'is_kicd_compulsory'  => false,
                            'min_periods'         => 2,
                            'max_periods'         => 3,
                            'kicd_code'           => '844-S58-AGR-001',
                        ],
                        [
                            'name'                => 'Home Science',
                            'code'                => '84-S58-HOM',
                            'category'            => 'Technical',
                            'learning_area'       => 'Applied Sciences',
                            'is_core'             => false,
                            'is_kicd_compulsory'  => false,
                            'min_periods'         => 2,
                            'max_periods'         => 3,
                            'kicd_code'           => '844-S58-HOM-001',
                        ],
                        [
                            'name'                => 'Art & Craft',
                            'code'                => '84-S58-ART',
                            'category'            => 'Creative Arts',
                            'learning_area'       => 'Creative Arts',
                            'is_core'             => false,
                            'is_kicd_compulsory'  => false,
                            'min_periods'         => 2,
                            'max_periods'         => 3,
                            'kicd_code'           => '844-S58-ART-001',
                        ],
                        [
                            'name'                => 'Music',
                            'code'                => '84-S58-MUS',
                            'category'            => 'Creative Arts',
                            'learning_area'       => 'Creative Arts',
                            'is_core'             => false,
                            'is_kicd_compulsory'  => false,
                            'min_periods'         => 1,
                            'max_periods'         => 2,
                            'kicd_code'           => '844-S58-MUS-001',
                        ],
                    ],
                ],

                // ── Secondary (Form 1–4) ───────────────────────────────────
                'secondary_844' => [
                    'level'       => 'Secondary',
                    'grade_level' => 'Form 1-4',
                    'pathway'     => null,
                    'subjects'    => [
                        // Compulsory subjects (all Form 1-4 students)
                        [
                            'name'                => 'English',
                            'code'                => '84-F14-ENG',
                            'category'            => 'Languages',
                            'learning_area'       => 'Languages',
                            'is_core'             => true,
                            'is_kicd_compulsory'  => true,
                            'min_periods'         => 5,
                            'max_periods'         => 5,
                            'kicd_code'           => '844-ENG-001',
                        ],
                        [
                            'name'                => 'Kiswahili',
                            'code'                => '84-F14-KIS',
                            'category'            => 'Languages',
                            'learning_area'       => 'Languages',
                            'is_core'             => true,
                            'is_kicd_compulsory'  => true,
                            'min_periods'         => 4,
                            'max_periods'         => 4,
                            'kicd_code'           => '844-KIS-001',
                        ],
                        [
                            'name'                => 'Mathematics',
                            'code'                => '84-F14-MAT',
                            'category'            => 'Mathematics',
                            'learning_area'       => 'Mathematics',
                            'is_core'             => true,
                            'is_kicd_compulsory'  => true,
                            'min_periods'         => 5,
                            'max_periods'         => 6,
                            'kicd_code'           => '844-MAT-001',
                        ],
                        [
                            'name'                => 'Biology',
                            'code'                => '84-F14-BIO',
                            'category'            => 'Sciences',
                            'learning_area'       => 'Sciences',
                            'is_core'             => true,
                            'is_kicd_compulsory'  => true,
                            'min_periods'         => 4,
                            'max_periods'         => 5,
                            'requires_lab'        => true,
                            'kicd_code'           => '844-BIO-001',
                        ],
                        [
                            'name'                => 'Physics',
                            'code'                => '84-F14-PHY',
                            'category'            => 'Sciences',
                            'learning_area'       => 'Sciences',
                            'is_core'             => true,
                            'is_kicd_compulsory'  => true,
                            'min_periods'         => 4,
                            'max_periods'         => 5,
                            'requires_lab'        => true,
                            'kicd_code'           => '844-PHY-001',
                        ],
                        [
                            'name'                => 'Chemistry',
                            'code'                => '84-F14-CHE',
                            'category'            => 'Sciences',
                            'learning_area'       => 'Sciences',
                            'is_core'             => true,
                            'is_kicd_compulsory'  => true,
                            'min_periods'         => 4,
                            'max_periods'         => 5,
                            'requires_lab'        => true,
                            'kicd_code'           => '844-CHE-001',
                        ],
                        [
                            'name'                => 'History & Government',
                            'code'                => '84-F14-HIS',
                            'category'            => 'Humanities',
                            'learning_area'       => 'Social Studies',
                            'is_core'             => false,
                            'is_kicd_compulsory'  => false,
                            'min_periods'         => 3,
                            'max_periods'         => 4,
                            'kicd_code'           => '844-HIS-001',
                        ],
                        [
                            'name'                => 'Geography',
                            'code'                => '84-F14-GEO',
                            'category'            => 'Humanities',
                            'learning_area'       => 'Social Studies',
                            'is_core'             => false,
                            'is_kicd_compulsory'  => false,
                            'min_periods'         => 3,
                            'max_periods'         => 4,
                            'kicd_code'           => '844-GEO-001',
                        ],
                        [
                            'name'                => 'Christian Religious Education',
                            'code'                => '84-F14-CRE',
                            'category'            => 'Humanities',
                            'learning_area'       => 'Religious Education',
                            'is_core'             => false,
                            'is_kicd_compulsory'  => false,
                            'min_periods'         => 3,
                            'max_periods'         => 4,
                            'kicd_code'           => '844-CRE-001',
                        ],
                        [
                            'name'                => 'Islamic Religious Education',
                            'code'                => '84-F14-IRE',
                            'category'            => 'Humanities',
                            'learning_area'       => 'Religious Education',
                            'is_core'             => false,
                            'is_kicd_compulsory'  => false,
                            'min_periods'         => 3,
                            'max_periods'         => 4,
                            'kicd_code'           => '844-IRE-001',
                        ],
                        [
                            'name'                => 'Business Studies',
                            'code'                => '84-F14-BUS',
                            'category'            => 'Technical',
                            'learning_area'       => 'Applied Sciences',
                            'is_core'             => false,
                            'is_kicd_compulsory'  => false,
                            'min_periods'         => 3,
                            'max_periods'         => 4,
                            'kicd_code'           => '844-BUS-001',
                        ],
                        [
                            'name'                => 'Agriculture',
                            'code'                => '84-F14-AGR',
                            'category'            => 'Technical',
                            'learning_area'       => 'Applied Sciences',
                            'is_core'             => false,
                            'is_kicd_compulsory'  => false,
                            'min_periods'         => 3,
                            'max_periods'         => 4,
                            'kicd_code'           => '844-AGR-001',
                        ],
                        [
                            'name'                => 'Home Science',
                            'code'                => '84-F14-HOM',
                            'category'            => 'Technical',
                            'learning_area'       => 'Applied Sciences',
                            'is_core'             => false,
                            'is_kicd_compulsory'  => false,
                            'min_periods'         => 3,
                            'max_periods'         => 4,
                            'kicd_code'           => '844-HOM-001',
                        ],
                        [
                            'name'                => 'Computer Studies',
                            'code'                => '84-F14-CST',
                            'category'            => 'Technical',
                            'learning_area'       => 'Science & Technology',
                            'is_core'             => false,
                            'is_kicd_compulsory'  => false,
                            'min_periods'         => 3,
                            'max_periods'         => 4,
                            'kicd_code'           => '844-CST-001',
                        ],
                        [
                            'name'                => 'Art & Design',
                            'code'                => '84-F14-ART',
                            'category'            => 'Creative Arts',
                            'learning_area'       => 'Creative Arts',
                            'is_core'             => false,
                            'is_kicd_compulsory'  => false,
                            'min_periods'         => 3,
                            'max_periods'         => 4,
                            'kicd_code'           => '844-ART-001',
                        ],
                        [
                            'name'                => 'Music',
                            'code'                => '84-F14-MUS',
                            'category'            => 'Creative Arts',
                            'learning_area'       => 'Creative Arts',
                            'is_core'             => false,
                            'is_kicd_compulsory'  => false,
                            'min_periods'         => 3,
                            'max_periods'         => 4,
                            'kicd_code'           => '844-MUS-001',
                        ],
                        [
                            'name'                => 'French',
                            'code'                => '84-F14-FRE',
                            'category'            => 'Languages',
                            'learning_area'       => 'Languages',
                            'is_core'             => false,
                            'is_kicd_compulsory'  => false,
                            'min_periods'         => 3,
                            'max_periods'         => 4,
                            'kicd_code'           => '844-FRE-001',
                        ],
                        [
                            'name'                => 'German',
                            'code'                => '84-F14-GER',
                            'category'            => 'Languages',
                            'learning_area'       => 'Languages',
                            'is_core'             => false,
                            'is_kicd_compulsory'  => false,
                            'min_periods'         => 3,
                            'max_periods'         => 4,
                            'kicd_code'           => '844-GER-001',
                        ],
                    ],
                ],
            ],
        ];
    }
}